version: '2'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=$PG_PASS
    volumes:
      - $PROD_PSQL_DATA_PATH:/var/lib/postgresql/data

  serv:
    volumes:
      - static:/code/bidsoup/bids/static
    ports:
      - "8000:80"

  backend:
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - POSTGRES_PASSWORD=$PG_PASS
    volumes:
      - static:/var/www/static
    command: /bin/bash /code/start-prod.sh

  frontend:
    volumes:
      - static:/var/www/static
    command: /bin/bash /usr/app/src/scripts/start-prod.sh


volumes:
  static:
